call npm install -g @types/jquery@^3.2.12
call npm install -g awesome-typescript-loader@^3.2.1
call npm install -g browserify@^14.4.0
call npm install -g babel-core@^6.26.0
call npm install -g babel-loader@^7.1.2
call npm install -g babel-preset-env@^1.6.0
call npm install -g babel-preset-es2015@^6.24.1
call npm install -g babel-preset-es2015-loose@^8.0.0
call npm install -g css-loader@^0.28.4
call npm install -g extract-text-webpack-plugin@^2.1.2
call npm install -g gulp@^3.9.1
call npm install -g gulp-clean-css@^3.9.0
call npm install -g gulp-concat@^2.6.1
call npm install -g gulp-plumber@^1.1.0
call npm install -g gulp-sass@^3.1.0
call npm install -g gulp-sourcemaps@^2.6.1
call npm install -g gulp-typescript@^3.2.2
call npm install -g gulp-uglify@^3.0.0
call npm install -g jshint@^2.9.5
call npm install -g node-sass@^4.5.3
call npm install -g sass-loader@^6.0.6
call npm install -g strip-css-comments@^3.0.0
call npm install -g style-loader@^0.18.2
call npm install -g ts-loader@^2.2.2
call npm install -g tsify@^3.0.3
call npm install -g typescript@^2.4.1
call npm install -g uglifyjs-webpack-plugin@^0.4.6
call npm install -g vinyl-buffer@^1.0.0
call npm install -g vinyl-source-stream@^1.1.0
call npm install -g watchify@^3.9.0
call npm install -g webpack@^3.0.0